name: petadopt
description: PetAdopt - Supabase + Clean Architecture demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State & navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Supabase
  supabase_flutter: ^2.6.0

  # Utils
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  intl: ^0.19.0

  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Maps & GPS (OpenStreetMap)
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # HTTP (Gemini)
  http: ^1.2.2

  # Extras (Google OAuth + Push)
  google_sign_in: ^6.2.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
